### PR TITLE
QoS changes

### PR DESCRIPTION
**Pull request by rotu**
Subscribe to laser and other sensor scans with Sensor Data QoS preset
Publish maps with durability=transient_local so late joiners can see the last published map

### CODE REVIEW

**Comment by Karsten1987** [comment]
is that tackling #28?

**Comment by rotu** [comment]
> is that tackling #28?

Yes.

**Comment by clalancette** [comment]
@rotu Sorry for the long silence here.  I think this PR makes sense, but it is actually using a mix of Crystal APIs and Dashing APIs.  Which would you prefer to target?  If the answer is "both", then I think we'll need to open two separate PRs to use different APIs for each.  If it is just dashing, then I think we can rebase this against the latest dashing (#31 probably causes merge conflicts), and change to using all dashing APIs.  Thanks!

**Comment by rotu** [comment]
Thanks for finally getting around to it. I've redone my changes on top of the dashing branch.

**Review by clalancette — APPROVED** [review]
Looks good to me.

**Pull request merged**
