### PR TITLE
Switch to using the RCUTILS_LOG macros.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
CI:

* Turtlebot [Build Status](http://ci.ros2.org/job/ci_turtlebot-demo_linux/98/)

**Comment by mikaelarguedas** [comment]
Shouldn't we wait to have stream logging implemented and use the stream macros then? (rather than changing the semantic of the logging variable while using the same name)

**Comment by clalancette** [comment]
> Shouldn't we wait to have stream logging implemented and use the stream macros then? (rather than changing the semantic of the logging variable while using the same name)

We could go that way, though there isn't much downside to this particular change.  Since cartographer_ros isn't really using streaming at all, and this is buried down in a C++ implementation, doing it this way doesn't really hurt anything.  We can always switch back to the stream one when it is implemented.  On the other hand, I don't have a strong feeling about it, so if you want to leave it at the current `std::cerr/cout`, that's OK too.

**Comment by mikaelarguedas** [comment]
I don't feel strongly about it.
My original assumption was that we were making these changes (rather than updating the "pure" ros2 examples or core ros2 packages) was to give a better example of how to convert packages while keeping the same semantic/behavior with a minimal diff. Is that correct ? If so I'd say let's update them with the final macros and not change semantic or do extra work if we know we will need to change them again soon.
Otherwise, I'm ok to merge this, maybe we can add a TODO to remind ourselves to update them in the future when the macros exist (ala https://github.com/ros2/joystick_drivers/blob/72bb90f88c7241013c8d4cacae24ca5798855392/joy/src/joy_node_linux.cpp#L47-L49)

**Comment by clalancette** [comment]
> My original assumption was that we were making these changes (rather than updating the "pure" ros2 examples or core ros2 packages) was to give a better example of how to convert packages while keeping the same semantic/behavior with a minimal diff. Is that correct ?

Yeah, that is the main reason to do this.  The other minor reason is so that all of the output gets the same look and feel, and gets output the same, etc.  But I agree with your reasoning, so I'll change this to not change the `_STREAM` macros.

**Comment by clalancette** [comment]
Actually, I'll just close this then :).

**Pull request closed without merging**
