### PR TITLE
Fix up dependencies.

### PR DESCRIPTION
**Pull request by clalancette**
While auditing the package for release, I found a number of
dependencies that weren't declared, or not declared entirely
properly.  There were also unnecessary dependencies declared.
This one fixes all of the ones I noticed, though it will *not*
tell us if we have missed a dependency that we need.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

@doisyg FYI; we'll need these fixes (or something like them) in order to release

### CODE REVIEW

**Comment by doisyg** [comment]
> @doisyg FYI; we'll need these fixes (or something like them) in order to release

What do you suggest ? That I start from this PR and fully re-audit the dependencies ?

**Comment by clalancette** [comment]
> What do you suggest ? That I start from this PR and fully re-audit the dependencies ?

That's the most sure way to get something working, but also the most work.  Instead, I think we can just start with this PR (I'm looking from an approval from you), and then I'll try to run a prerelease to see what happens.  We may need to iterate one or two more times after that.

**Comment by doisyg** [comment]
> Instead, I think we can just start with this PR (I'm looking from an approval from you), and then I'll try to run a prerelease to see what happens

Good plan. The first round of clean up looks already much better. Do you want me to check locally for compilation before merging ?

**Comment by clalancette** [comment]
> Good plan. The first round of clean up looks already much better. Do you want me to check locally for compilation before merging ?

Yeah, may as well.  At least that's a little better than "it works for me!" :).

Let me know when you've done that (and if you were successful), and then I'll go ahead and merge this.

**Comment by doisyg** [comment]
Compiling fine and sanity check okay on the museum bag with `jammy` and `rolling` last debs. All dependencies were previously installed (i.e. I did NOT do the checks on a fresh system)

**Comment by clalancette** [comment]
> Compiling fine and sanity check okay on the museum bag with `jammy` and `rolling` last debs. All dependencies were previously installed (i.e. I did do the checks on a fresh system)

OK, sounds good!  Thanks for the additional check, I'll go ahead and merge this and attempt a prerelease.

**Comment by clalancette** [comment]
All right, it looks like my prerelease was successful.  I'm going to open one more PR to bump the version numbers, merge that, tag, and then try a release on the actual buildfarm.

**Comment by doisyg** [comment]
Great, thanks for the help! Once released I plan to make an announcement on Discourse + a call for testing. And I will fix potential bugs if they appear with the goal of reaching the same level of functionality/reliability we had on ros1 (I believe we are already there but this is without extensive tests outside my use-cases).

**Comment by clalancette** [comment]
All right, it's made it through the build system, and it is installable as `ros-rolling-cartographer-ros` on Ubuntu 22.04 from the `ros-testing` repository now.  If you want to give it a whirl, that would be awesome.

**Comment by doisyg** [comment]
I can confirm that the version from `ros-testing` is working just fine

**Comment by clalancette** [comment]
> I can confirm that the version from `ros-testing` is working just fine

Fantastic, thanks for the testing and all of your work getting this done!

**Pull request merged**
